
import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'ru' | 'ua' | 'de';

type Translations = {
  [key: string]: string;
};

const translations: Record<Language, Translations> = {
  ua: {
    nav_audience: "Цільова аудиторія",
    nav_process: "Процес",
    nav_pricing: "Вартість",
    nav_cta: "Почати аналіз",
    nav_lang: "Мова",
    nav_profile: "Профіль канцелярії",
    hero_title_1: "Найнадійніший спосіб",
    hero_title_2: "змінити статус з § 24 AufenthG на постійну посвідку на проживання",
    hero_subtitle: "Ваше завдання — побачити свій шлях. Все інше — наша работа.",
    hero_cta: "Індивідуальний аналіз",
    hero_trust_anwalt: "на Anwalt.de",
    hero_trust_exp: "Років досвіду",
    hero_trust_won: "Проведених справ",
    hero_trust_office: "Адвокатська канцелярія",
    hero_video_label: "НАША РОБОТА",
    hero_video_sub: "1 хв",
    hero_video_id: "rCclb5-nKlw",
    hero_open_youtube: "Дивитися на YouTube",
    b2_title: "Чому так складно зрозуміти, який шлях правильний при § 24 AufenthG",
    b2_static_p1: "Проблема §24 не в самому статусі, а у вашій індивідуальній ситуації.",
    b2_static_p2: "Вік, сім'я, освіта, професійний досвід, рівень мови, пропозиції роботи та дохід — усі ці фактори мають значення лише в певних комбінаціях.",
    b2_static_p3: "Тому не існує універсальної відповіді на питання, як змінити §24 на інший статус.",
    b2_static_p4: "Без системного аналізу ви втрачаєте дорогоцінний час, просто чекаючи.",
    b2_acc1_t: "Чому один і той самий параграф підходить не всім",
    b2_acc1_txt: "У міграційному праві немає універсальних рішений. Те, що здається ідеальним для одного, може бути зовсім непридатним для іншого.",
    b2_acc2_t: "Значення віку, доходу та мови",
    b2_acc2_txt: "Вік, рівень доходу та знання мови можуть посилити певні варіанти або повністю заблокувати їх.",
    b2_acc3_t: "Чому визнання освіти змінює стратегію",
    b2_acc3_txt: "Одного диплома часто недостатньо. Важливо, чи визнаний він у Німеччині повністю, частково або не визнаний взагалі.",
    b2_acc4_t: "Вплив сімейної ситуації",
    b2_acc4_txt: "Чоловік/дружина та діти змінюють вимоги до доходу та можуть відкрити додаткові правові підстави.",
    b2_acc5_t: "Професійний досвід проти пропозиції роботи",
    b2_acc5_txt: "Обидва фактори оцінюються по-різному залежно від обраного статусу.",
    b2_acc6_t: "Перевага послідовного аналізу",
    b2_acc6_txt: "Сервіс виключає невідповідні шляхи, розставляє пріоритети та вказує на критичні умови.",
    b3_title: "Використовуйте адвокатську логіку для ваших можливостей",
    b3_intro: "Paragraf24 — це цифровий сервіс від Klamert & Partner Rechtsanwälte, Мюнхен. Він забезпечує правову ясність у вашій ситуації.",
    b3_s1_t: "Опис ситуації",
    b3_s1_txt: "Коректно дайте відповіді на питання про вік, сім'ю, освіту, мову та дохід.",
    b3_s2_t: "Адвокатський аналіз",
    b3_s2_txt: "Сервіс використовує правову логіку, щоб ідентифікувати відповідні та виключити невідповідні шляхи переходу.",
    b3_s3_t: "Чіткий результат",
    b3_s3_txt: "Ви отримаєте дорожню карту з варіантами переходу та чек-листом необхідних документів.",
    b3_outro: "Paragraf24 забезпечує впевненість ще до фактичної подачі заяви.",
    b4_title: "Результат для самостійних дій",
    b4_intro: "Індивідуальний аналіз — це фундамент для свідомого переходу з §24 в інший безстроковий законний статус.",
    b4_r1_t: "Індивідуальна стратегія переходу",
    b4_r1_txt: "Дізнайтеся свій оптимальний шлях і чому він має сенс саме у вашій ситуації.",
    b4_r2_t: "Вимоги та ризики",
    b4_r2_txt: "Побачте критичні умови та кроки, які можуть призвести до відмови.",
    b4_r3_t: "Пакет для подачі",
    b4_r3_txt: "Отримайте чек-листи та форми для самостійної подачі заяви.",
    b4_r4_t: "Свідоме рішення",
    b4_r4_txt: "Приймайте рішення на основі фактів, а не припущень.",
    b4_trans_t: "Перехід до реалізації",
    b4_trans_txt: "Після отримання стратегії ви можете обрати повний супровід вашої справи.",
    b4_logic_txt: "Логіка сервісу побудована на актуальній судовій практиці Німеччини.",
    b5_title: "ПАКЕТИ ПОСЛУГ",
    b5_subtitle: "Прозоре ціноутворення. Єдина точка входу.",
    b5_badge_locked: "Доступно після аналізу",
    b5_p1_title: "Пакет №1 «Стартовий»",
    b5_p1_sub: "Юридична орієнтація та стратегія",
    b5_p1_desc: "Правова оцінка вашої ситуації та можливих ризиків.",
    b5_p1_f1: "Індивідуальна правова оцінка",
    b5_p1_f2: "Стратегія переходу",
    b5_p1_f3: "Аналіз параграфів",
    b5_p1_f4: "Оцінка готовності",
    b5_p1_cta: "Почати",
    b5_p2_title: "Пакет №2 «Реалізація»",
    b5_p2_sub: "Адміністративний супровід",
    b5_p2_desc: "Повна підготовка та подача документів до відомства.",
    b5_p2_f1: "Заповнення всіх анкет",
    b5_p2_f2: "Перевірка документів",
    b5_p2_f3: "Подача заяви",
    b5_p2_f4: "Комунікація з владою",
    b5_p2_cta: "Обрати",
    b5_p3_title: "Пакет №3 «Преміум»",
    b5_p3_sub: "Адвокатський захист",
    b5_p3_desc: "Максимальний захист ваших інтересів адвокатом.",
    b5_p3_f1: "Все з Пакету №2",
    b5_p3_f2: "Адвокатські запити",
    b5_p3_f3: "Пріоритетна обробка",
    b5_p3_f4: "Захист від затримок",
    b5_p3_f5: "Контроль термінів",
    b5_p3_cta: "Обрати",
    b5_p4_title: "Пакет №4 «Суд»",
    b5_p4_sub: "Судове представництво",
    b5_p4_desc: "Вирішення складних випадків через суд.",
    b5_p4_f1: "Подача позову",
    b5_p4_f2: "Представництво в суді",
    b5_p4_f3: "Оскарження відмов",
    b5_p4_cta: "Обрати",
    checkout_preorder_title: "Попереднє замовлення",
    checkout_name: "Ім'я",
    checkout_surname: "Прізвище",
    checkout_email: "Email",
    checkout_phone: "Телефон",
    checkout_family_mode: "Сімейний формат",
    checkout_spouse: "Чоловік/Дружина",
    checkout_children: "Діти",
    checkout_previous_pkgs: "Раніше оплачені пакети",
    checkout_base_price: "Базова ціна",
    checkout_family_addon: "Доплата за сім'ю",
    checkout_credit_prefix: "Залік",
    checkout_total: "Разом до сплати",
    checkout_confirm_p1: "Я розумію, що цей пакет є наступним кроком",
    checkout_confirm_p1_sub: "Для заліку вартості необхідно підтвердити попередній етап",
    checkout_confirm_p1_starter: "Я підтверджую правильність введених даних",
    checkout_btn_continue: "Продовжити",
    checkout_required_fields: "* Обов'язкові поля",
    b6_title: "Ризики та застереження",
    b6_lead: "Зміна статусу — це складний юридичний процес. Ось що ви повинні знати.",
    b6_consequence: "Наслідок",
    b6_meaning: "Що це означає",
    b6_solution_label: "Як ми це вирішуємо",
    b6_steps: "Кожен крок аналізується індивідуально",
    b6_accent_1: "Ваш статус §24 є тимчасовим",
    b6_accent_2: "Ми допомагаємо зробити його постійним",
    b6_r1_t: "Відмова у зміні статусу",
    b6_r1_c: "Втрата часу та грошей",
    b6_r1_d: "Відомство може відмовити, якщо умови виконані не повністю.",
    b6_r1_s: "Ми проводимо перевірку до подачі документів.",
    b6_r2_t: "Недостатній дохід",
    b6_r2_c: "Блокування переходу",
    b6_r2_d: "Для багатьох статусів потрібен стабільний дохід на всю сім'ю.",
    b6_r2_s: "Розраховуємо необхідний дохід індивідуально.",
    b6_r3_t: "Проблеми з дипломом",
    b6_r3_c: "Неможливість робочої візи",
    b6_r3_d: "Диплом має бути визнаний у Німеччині (Anabin).",
    b6_r3_s: "Перевіряємо ваш диплом у базі Anabin.",
    b6_r4_t: "Затримки обробки",
    b6_r4_c: "Невизначеність",
    b6_r4_d: "Відомства перевантажені, розгляд може тривати місяцями.",
    b6_r4_s: "Використовуємо юридичні інструменти прискорення.",
    b6_r5_t: "Вимоги до мови",
    b6_r5_c: "Невідповідність критеріям",
    b6_r5_d: "Часто потрібен сертифікат рівня B1 або вище.",
    b6_r5_s: "Вказуємо на необхідний рівень для вашого шляху.",
    b6_r6_t: "Сімейні обставини",
    b6_r6_c: "Зміна стратегії",
    b6_r6_d: "Склад сім'ї впливає на вимоги до житла та грошей.",
    b6_r6_s: "Аналізуємо кейс усієї родини разом.",
    final_cta_title: "Готові почати свій шлях до ПМЖ?",
    final_cta_lead: "Не чекайте 2027 року. Почніть перехід вже сьогодні.",
    final_cta_btn: "Отримати індивідуальну стратегію",
    final_cta_sub: "Оплата через захищений шлюз Stripe",
    final_cta_trust: "Довіряйте професіоналам Klamert & Partner",
    faq_title: "Часті питання",
    faq_q1: "Що якщо результат аналізу буде негативним?",
    faq_a1: "Ми вкажемо вам, що саме потрібно зробити, щоб відповідати умовам у майбутньому.",
    faq_q2: "Скільки часу займає аналіз?",
    faq_a2: "Зазвичай ви отримуєте результат протягом 24-48 годин.",
    faq_q3: "Чи можу я відразу подаватися на ПМЖ?",
    faq_a3: "Це залежатиме від вашого рівня доходу, терміну перебування та знання мови. Аналіз покаже ваші шанси.",
    faq_q4: "Що якщо у мене є робота, но немає диплома?",
    faq_a4: "Існують шляхи для досвідчених фахівців. Ми перевіримо вашу ситуацію.",
    faq_q5: "Чому я повинен спочатку купити Стартовий?",
    faq_a5: "Без аналізу ми не можемо відповідально судити про те, який шлях для вас є здійсненним.",
    faq_q6: "Чи безпечні мої дані?",
    faq_a6: "Так, мы використовуємо зашифровані з'єднання та суворо дотримуємося правил GDPR.",
    faq_q7: "Чи можу я включити в аналіз батьків?",
    faq_a7: "Зазвичай батьки не входять до основної сімейної групи, але ми перевіримо вашу ситуацію.",
    faq_footer: "Наша мета — ваш чіткий та безпечний шлях.",
    footer_brand_desc: "Адвокатський сервіс для переходу з § 24 AufenthG на стійкі види на проживання в Німеччині.",
    footer_legal_title: "Юридична інформація",
    footer_bottom_text: "БЕЗПЕКА. ЯСНІСТЬ. РЕЗУЛЬТАТ.",
    footer_link_impressum: "Impressum",
    footer_link_datenschutz: "Datenschutz",
    footer_link_agb: "AGB",
    footer_link_widerruf: "Widerruf",
    footer_link_preise: "Ціни",
    footer_anbieter_title: "Провайдер",
    footer_anbieter_name: "Kanzlei Klamert & Partner",
    footer_anbieter_addr: "München, Deutschland",
    footer_anbieter_phone: "+49 (0) 89 123 456",
    footer_anbieter_contact: "contact@paragraf24.de",
    footer_anbieter_chamber: "Зареєстровано в Адвокатській палаті Мюнхена",
    footer_anbieter_title_professional: "Rechtsanwälte (ФРН)",
    footer_notice_title: "Важливе повідомлення",
    footer_notice_text: "Інформація на цьому сайті не є індивідуальною юридичною консультацією до моменту замовлення пакету послуг та укладення договору.",
    proc_title: "Процес",
    proc_subtitle: "Три кроки до вашого нового статусу",
    proc_step1_title: "Аналіз",
    proc_step1_desc: "Визначення кращих варіантів зміни статусу.",
    proc_step2_title: "Подача",
    proc_step2_desc: "Підготовка документів до відомства.",
    proc_step3_title: "Супровід",
    proc_step3_desc: "Адвокатська підтримка при затримках.",
    proc_bottom: "Аналіз — основа для будь-якого переходу.",
    aud_title: "Кому ми допомагаємо",
    aud_subtitle: "Тим, хто хоче перетворити тимчасовий статус на постійний",
    aud_box_title: "Ви перебуваєте в Німеччині за §24 і:",
    aud_list_1: "Маєте роботу або пропозицію",
    aud_list_2: "Маєте власний бізнес",
    aud_list_3: "Учитесь або плануєте",
    aud_list_4: "Маєте сім'ю в Німеччині",
    aud_list_5: "Володієте мовою",
    aud_quote: "«Ваше завдання — інтегруватися, наше — юридично закріпити успіх»"
  },
  ru: {
    nav_audience: "Целевая аудитория",
    nav_process: "Процесс",
    nav_pricing: "Стоимость",
    nav_cta: "Начать анализ",
    nav_lang: "Язык",
    nav_profile: "Профиль канцелярии",
    hero_title_1: "Самый надежный способ",
    hero_title_2: "перейти с § 24 AufenthG на постоянный статус проживания",
    hero_subtitle: "Ваша задача — увидеть свой путь. Все остальное — наша работа.",
    hero_cta: "Индивидуальный анализ",
    hero_trust_anwalt: "на Anwalt.de",
    hero_trust_exp: "Лет опыта",
    hero_trust_won: "Проведенных дел",
    hero_trust_office: "Адвокатская канцелярия",
    hero_video_label: "НАША РОБОТА",
    hero_video_sub: "1 мин",
    hero_video_id: "rCclb5-nKlw",
    hero_open_youtube: "Смотреть на YouTube",
    b2_title: "Почему так сложно понять, какой путь правильный при § 24 AufenthG",
    b2_static_p1: "Проблема §24 не в самом статусе, а в вашей индивидуальной ситуации.",
    b2_static_p2: "Возраст, семья, образование, опыт, язык и доход важны только в комбинациях.",
    b2_static_p3: "Не существует универсального ответа на вопрос о смене статуса.",
    b2_static_p4: "Без системного анализа вы теряете время, просто ожидая.",
    b2_acc1_t: "Почему один и тот же параграф подходит не всем",
    b2_acc1_txt: "В миграционном праве нет универсальных решений. То, что подходит одному, не годится другому.",
    b2_acc2_t: "Значение возраста, дохода и языка",
    b2_acc2_txt: "Эти факторы могут как открыть определенные варианты, так и полностью заблокировать их.",
    b2_acc3_t: "Почему признание образования меняет стратегию",
    b2_acc3_txt: "Важно, признан ли ваш диплом в Германии полностью, частично или не признан вовсе.",
    b2_acc4_t: "Влияние семейной ситуации",
    b2_acc4_txt: "Супруги и дети меняют требования к доходу и могут открыть новые правовые основания.",
    b2_acc5_t: "Профессиональный опыт против предложения о работе",
    b2_acc5_txt: "Оба фактора оцениваются по-разному в зависимости от выбранного статуса.",
    b2_acc6_t: "Преимущество последовательного анализа",
    b2_acc6_txt: "Сервис исключает тупиковые пути и расставляет приоритеты.",
    b3_title: "Используйте адвокатскую логику для ваших возможностей",
    b3_intro: "Paragraf24 — это цифровой сервис от Klamert & Partner Rechtsanwälte, Мюнхен. Он обеспечивает правовой ясность в вашей ситуации.",
    b3_s1_t: "Описание ситуации",
    b3_s1_txt: "Корректно ответьте на вопросы о возрасте, семье, образовании, языке и доходе.",
    b3_s2_t: "Адвокатский анализ",
    b3_s2_txt: "Сервис использует правовую логику для идентификации подходящих путей перехода.",
    b3_s3_t: "Четкий результат",
    b3_s3_txt: "Вы получите дорожную карту с вариантами перехода и чек-листом документов.",
    b3_outro: "Paragraf24 обеспечивает уверенность еще до подачи заявления.",
    b4_title: "Результат для самостоятельных действий",
    b4_intro: "Индивидуальный анализ — фундамент для осознанного перехода.",
    b4_r1_t: "Индивидуальная стратегия перехода",
    b4_r1_txt: "Узнайте свой оптимальный путь и почему он имеет смысл в вашей ситуации.",
    b4_r2_t: "Требования и риски",
    b4_r2_txt: "Увидьте критические условия и шаги, которые могут привести к отказу.",
    b4_r3_t: "Пакет для подачи",
    b4_r3_txt: "Получите чек-листы и формы для самостоятельной подачи заявления.",
    b4_r4_t: "Осознанное решение",
    b4_r4_txt: "Принимайте решения на основе фактов, а не предположений.",
    b4_trans_t: "Переход к реализации",
    b4_trans_txt: "После получения стратегии вы можете выбрать полное сопровождение вашего дела.",
    b4_logic_txt: "Логика сервиса построена на актуальной судебной практике Германии.",
    b5_title: "ПАКЕТЫ УСЛУГ",
    b5_subtitle: "Прозрачное ценообразование. Единая точка входа.",
    b5_badge_locked: "Доступно после анализа",
    b5_p1_title: "Пакет №1 «Стартовый»",
    b5_p1_sub: "Юридическая ориентация и стратегия",
    b5_p1_desc: "Правовая оценка вашей ситуации и возможных рисков.",
    b5_p1_f1: "Индивидуальная правовая оценка",
    b5_p1_f2: "Стратегия перехода",
    b5_p1_f3: "Анализ параграфов",
    b5_p1_f4: "Оценка готовности",
    b5_p1_cta: "Начать",
    b5_p2_title: "Пакет №2 «Реализация»",
    b5_p2_sub: "Административное сопровождение",
    b5_p2_desc: "Полная подготовка и подача документов в ведомство.",
    b5_p2_f1: "Заполнение всех анкет",
    b5_p2_f2: "Проверка документов",
    b5_p2_f3: "Подача заявления",
    b5_p2_f4: "Коммуникация с властями",
    b5_p2_cta: "Выбрать",
    b5_p3_title: "Пакет №3 «Премиум»",
    b5_p3_sub: "Адвокатская защита",
    b5_p3_desc: "Максимальная защита ваших интересов адвокатом.",
    b5_p3_f1: "Все из Пакета №2",
    b5_p3_f2: "Адвокатские запросы",
    b5_p3_f3: "Приоритетная обработка",
    b5_p3_f4: "Защита от задержек",
    b5_p3_f5: "Контроль сроков",
    b5_p3_cta: "Выбрать",
    b5_p4_title: "Пакет №4 «Суд»",
    b5_p4_sub: "Судебное представительство",
    b5_p4_desc: "Решение сложных случаев через суд.",
    b5_p4_f1: "Подача иска",
    b5_p4_f2: "Представительство в суде",
    b5_p4_f3: "Обжалование отказов",
    b5_p4_cta: "Выбрать",
    checkout_preorder_title: "Предварительный заказ",
    checkout_name: "Имя",
    checkout_surname: "Фамилия",
    checkout_email: "Email",
    checkout_phone: "Телефон",
    checkout_family_mode: "Семейный формат",
    checkout_spouse: "Супруг/Супруга",
    checkout_children: "Дети",
    checkout_previous_pkgs: "Ранее оплаченные пакеты",
    checkout_base_price: "Базовая цена",
    checkout_family_addon: "Доплата за семью",
    checkout_credit_prefix: "Зачет",
    checkout_total: "Итого к оплате",
    checkout_confirm_p1: "Я понимаю, что этот пакет является следующим шагом",
    checkout_confirm_p1_sub: "Для зачета стоимости необходимо подтвердить предыдущий этап",
    checkout_confirm_p1_starter: "Я подтверждаю правильность введенных данных",
    checkout_btn_continue: "Продолжить",
    checkout_required_fields: "* Обязательные поля",
    b6_title: "Риски и предостережения",
    b6_lead: "Смена статуса — это сложный юридический процесс. Вот что вы должны знать.",
    b6_consequence: "Последствие",
    b6_meaning: "Что это значит",
    b6_solution_label: "Как мы это решаем",
    b6_steps: "Каждый шаг анализируется индивидуально",
    b6_accent_1: "Ваш статус §24 является временным",
    b6_accent_2: "Мы помогаем сделать его постоянным",
    b6_r1_t: "Отказ в смене статуса",
    b6_r1_c: "Потеря времени и денег",
    b6_r1_d: "Ведомство может отказать, если условия выполнены не полностью.",
    b6_r1_s: "Мы проводим проверку до подачи документов.",
    b6_r2_t: "Недостаточный доход",
    b6_r2_c: "Блокировка перехода",
    b6_r2_d: "Для многих статусов требуется стабильный доход на всю семью.",
    b6_r2_s: "Рассчитываем необходимый доход индивидуально.",
    b6_r3_t: "Проблемы с дипломом",
    b6_r3_c: "Невозможность рабочей визы",
    b6_r3_d: "Диплом должен быть признан в Германии (Anabin).",
    b6_r3_s: "Проверяем ваш диплом в базе Anabin.",
    b6_r4_t: "Задержки обработки",
    b6_r4_c: "Неопределенность",
    b6_r4_d: "Ведомства перегружены, рассмотрение может длиться месяцами.",
    b6_r4_s: "Используем юридические инструменты ускорения.",
    b6_r5_t: "Требования к языку",
    b6_r5_c: "Несоответствие критериям",
    b6_r5_d: "Часто требуется сертификат уровня B1 или выше.",
    b6_r5_s: "Указываем на необходимый уровень для вашего пути.",
    b6_r6_t: "Семейные обстоятельства",
    b6_r6_c: "Смена стратегии",
    b6_r6_d: "Состав семьи влияет на требования к жилью и деньгам.",
    b6_r6_s: "Анализируем кейс всей семьи вместе.",
    final_cta_title: "Готовы начать свой путь к ПМЖ?",
    final_cta_lead: "Не ждите 2027 года. Начните переход уже сегодня.",
    final_cta_btn: "Получить индивидуальную стратегию",
    final_cta_sub: "Оплата через защищенный шлюз Stripe",
    final_cta_trust: "Доверяйте профессионалам Klamert & Partner",
    faq_title: "Часто задаваемые вопросы",
    faq_q1: "Что если результат анализа будет отрицательным?",
    faq_a1: "Мы укажем вам, что именно нужно сделать, чтобы соответствовать условиям в будущем.",
    faq_q2: "Сколько времени занимает анализ?",
    faq_a2: "Обычно вы получаете результат в течение 24-48 часов.",
    faq_q3: "Могу ли я сразу подаваться на ПМЖ?",
    faq_a3: "Это зависит от вашего дохода и знания языка. Анализ покажет ваши шансы.",
    faq_q4: "Что если у меня есть работа, но нет диплома?",
    faq_a4: "Существуют пути для опытных специалистов. Мы проверим вашу ситуацию.",
    faq_q5: "Почему я должен сначала купить Стартовый?",
    faq_a5: "Без анализа невозможно ответственно судить о реальных путях.",
    faq_q6: "Безопасны ли мои данные?",
    faq_a6: "Да, мы используем зашифрованные соединения и строго соблюдаем правила GDPR.",
    faq_q7: "Могу ли я включить в анализ родителей?",
    faq_a7: "Обычно родители не входят в основную семейную группу, но мы проверим вашу ситуацию.",
    faq_footer: "Наша цель — ваш четкий и безопасный путь.",
    footer_brand_desc: "Адвокатский сервис для перехода с § 24 AufenthG на устойчивые виды на жительство в Германии.",
    footer_legal_title: "Юридическая информация",
    footer_bottom_text: "БЕЗОПАСНОСТЬ. ЯСНОСТЬ. РЕЗУЛЬТАТ.",
    footer_link_impressum: "Impressum",
    footer_link_datenschutz: "Datenschutz",
    footer_link_agb: "AGB",
    footer_link_widerruf: "Widerruf",
    footer_link_preise: "Цены",
    footer_anbieter_title: "Провайдер",
    footer_anbieter_name: "Kanzlei Klamert & Partner",
    footer_anbieter_addr: "München, Deutschland",
    footer_anbieter_phone: "+49 (0) 89 123 456",
    footer_anbieter_contact: "contact@paragraf24.de",
    footer_anbieter_chamber: "Зарегистрировано в Адвокатской палате Мюнхена",
    footer_anbieter_title_professional: "Rechtsanwälte (ФРГ)",
    footer_notice_title: "Важное сообщение",
    footer_notice_text: "Информация на данном сайте не является индивидуальной юридической консультацией до момента заказа пакета услуг и заключения договора.",
    proc_title: "Процесс",
    proc_subtitle: "Три шага к вашему новому статусу",
    proc_step1_title: "Анализ",
    proc_step1_desc: "Определение лучших вариантов смены статуса.",
    proc_step2_title: "Подача",
    proc_step2_desc: "Подготовка документов в ведомство.",
    proc_step3_title: "Сопровождение",
    proc_step3_desc: "Адвокатская поддержка при задержках.",
    proc_bottom: "Анализ — основа для любого перехода.",
    aud_title: "Кому мы помогаем",
    aud_subtitle: "Тем, кто хочет превратить временный статус в постоянный",
    aud_box_title: "Вы находитесь в Германии по §24 и:",
    aud_list_1: "Имеете работу или предложение",
    aud_list_2: "Имеете свой бизнес",
    aud_list_3: "Учитесь или планируете",
    aud_list_4: "Имеете семью в Германии",
    aud_list_5: "Владеете языком",
    aud_quote: "«Ваша задача — интегрироваться, наша — юридически закрепить успех»"
  },
  de: {
    nav_audience: "Zielgruppe",
    nav_process: "Prozess",
    nav_pricing: "Preise",
    nav_cta: "Analyse starten",
    nav_lang: "Sprache",
    nav_profile: "Kanzleiprofil",
    hero_title_1: "Der sicherste Weg,",
    hero_title_2: "eines Wechsels von § 24 AufenthG zu einem dauerhaften Status",
    hero_subtitle: "Ihre Aufgabe ist es, Ihren Weg zu erkennen. Alles andere ist unsere Arbeit.",
    hero_cta: "Individuelle Analyse",
    hero_trust_anwalt: "auf Anwalt.de",
    hero_trust_exp: "Jahre Erfahrung",
    hero_trust_won: "Geführte Verfahren",
    hero_trust_office: "Rechtsanwaltskanzlei",
    hero_video_label: "UNSERE ARBEIT",
    hero_video_sub: "1 Min",
    hero_video_id: "rCclb5-nKlw",
    hero_open_youtube: "Auf YouTube ansehen",
    b2_title: "Warum es so schwierig ist, zu verstehen welcher Weg der Richtige ist",
    b2_static_p1: "Das Problem liegt nicht im Status §24 selbst, sondern in Ihrer Situation.",
    b2_static_p2: "Alter, Familie, Bildung, Erfahrung, Sprache und Einkommen zählen nur in bestimmten Kombinationen.",
    b2_static_p3: "Es gibt keine universelle Antwort auf die Frage nach dem Statuswechsel.",
    b2_static_p4: "Ohne systematische Analyse verliert man wertvolle Zeit durch Abwarten.",
    b2_acc1_t: "Warum derselbe Paragraph nicht für jeden passt",
    b2_acc1_txt: "Im Migrationsrecht gibt es keine Universallösungen. Was für den einen passt, gilt nicht für andere.",
    b2_acc2_t: "Bedeutung von Alter, Einkommen und Sprache",
    b2_acc2_txt: "Diese Faktoren können Optionen verstärken oder komplett blockieren.",
    b2_acc3_t: "Warum Bildungsanerkennung die Strategie ändert",
    b2_acc3_txt: "Entscheidend ist, ob Ihr Abschluss in Deutschland anerkannt ist.",
    b2_acc4_t: "Einfluss der familiären Situation",
    b2_acc4_txt: "Ehepartner und Kinder ändern die Einkommensanforderungen erheblich.",
    b2_acc5_t: "Berufserfahrung vs. Jobangebot",
    b2_acc5_txt: "Beides wird je nach gewähltem Status unterschiedlich gewichtet.",
    b2_acc6_t: "Vorteil einer konsequenten Analyse",
    b2_acc6_txt: "Der Service schließt ungeeignete Wege aus und setzt klare Prioritäten.",
    b3_title: "Nutzen Sie anwaltliche Logik für Ihre Möglichkeiten",
    b3_intro: "Paragraf24 ist ein digitaler Service von Klamert & Partner Rechtsanwälte, München.",
    b3_s1_t: "Situation beschreiben",
    b3_s1_txt: "Beantworten Sie Fragen zu Alter, Familie, Bildung, Sprache und Einkommen korrekt.",
    b3_s2_t: "Anwaltliche Analyse",
    b3_s2_txt: "Der Service nutzt rechtliche Logik zur Identifizierung geeigneter Wechselwege.",
    b3_s3_t: "Klares Ergebnis",
    b3_s3_txt: "Sie erhalten eine Roadmap mit Wechseloptionen und einer Checkliste.",
    b3_outro: "Paragraf24 bietet Sicherheit vor der eigentlichen Antragstellung.",
    b4_title: "Ergebnis für eigenständiges Handeln",
    b4_intro: "Die individuelle Analyse ist das Fundament für einen bewussten Wechsel.",
    b4_r1_t: "Individuelle Wechselstrategie",
    b4_r1_txt: "Erkennen Sie Ihren optimalen Weg basierend auf Fakten.",
    b4_r2_t: "Anforderungen & Risiken",
    b4_r2_txt: "Sehen Sie kritische Bedingungen, die zu Ablehnungen führen könnten.",
    b4_r3_t: "Einreichungs-Set",
    b4_r3_txt: "Erhalten Sie Checklisten und Formulare für Ihren Antrag.",
    b4_r4_t: "Bewusste Entscheidung",
    b4_r4_txt: "Treffen Sie Entscheidungen basierend auf Fakten, nicht auf Vermutungen.",
    b4_trans_t: "Übergang zur Umsetzung",
    b4_trans_txt: "Nach Erhalt der Strategie können Sie eine vollständige Begleitung wählen.",
    b4_logic_txt: "Die Logik des Service basiert auf aktueller Rechtsprechung in Deutschland.",
    b5_title: "SERVICE-PAKETE",
    b5_subtitle: "Transparente Preisgestaltung. Ein einziger Einstiegspunkt.",
    b5_badge_locked: "Nach Analyse verfügbar",
    b5_p1_title: "Paket Nr. 1 «Starter»",
    b5_p1_sub: "Juristische Orientierung und Strategie",
    b5_p1_desc: "Rechtliche Bewertung Ihrer Situation und möglicher Risiken.",
    b5_p1_f1: "Individuelle rechtliche Bewertung",
    b5_p1_f2: "Strategie einer Statusänderung",
    b5_p1_f3: "Paragraphenanalyse",
    b5_p1_f4: "Bereitschaftsbewertung",
    b5_p1_cta: "Starten",
    b5_p2_title: "Paket Nr. 2 «Umsetzung»",
    b5_p2_sub: "Administrative Begleitung",
    b5_p2_desc: "Vollständige Vorbereitung und Einreichung der Unterlagen.",
    b5_p2_f1: "Ausfüllen aller Formulare",
    b5_p2_f2: "Dokumentenprüfung",
    b5_p2_f3: "Antragstellung",
    b5_p2_f4: "Behördenkommunikation",
    b5_p2_cta: "Wählen",
    b5_p3_title: "Paket Nr. 3 «Premium»",
    b5_p3_sub: "Anwaltlicher Schutz",
    b5_p3_desc: "Maximaler Schutz Ihrer Interessen durch einen Anwalt.",
    b5_p3_f1: "Alles aus Paket Nr. 2",
    b5_p3_f2: "Anwaltliche Anfragen",
    b5_p3_f3: "Priorisierte Bearbeitung",
    b5_p3_f4: "Schutz vor Verzögerungen",
    b5_p3_f5: "Fristenkontrolle",
    b5_p3_cta: "Wählen",
    b5_p4_title: "Paket Nr. 4 «Gericht»",
    b5_p4_sub: "Gerichtliche Vertretung",
    b5_p4_desc: "Lösung komplexer Fälle vor Gericht.",
    b5_p4_f1: "Klageeinreichung",
    b5_p4_f2: "Gerichtliche Vertretung",
    b5_p4_f3: "Widerspruchsverfahren",
    b5_p4_cta: "Wählen",
    checkout_preorder_title: "Vorbestellung",
    checkout_name: "Vorname",
    checkout_surname: "Nachname",
    checkout_email: "E-Mail",
    checkout_phone: "Telefon",
    checkout_family_mode: "Familienformat",
    checkout_spouse: "Ehepartner",
    checkout_children: "Kinder",
    checkout_previous_pkgs: "Bereits bezahlte Pakete",
    checkout_base_price: "Grundpreis",
    checkout_family_addon: "Familienzuschlag",
    checkout_credit_prefix: "Anrechnung",
    checkout_total: "Gesamtbetrag",
    checkout_confirm_p1: "Ich verstehe, dass dieses Paket der nächste Schritt ist",
    checkout_confirm_p1_sub: "Zur Preisberechnung muss die vorherige Phase bestätigt werden",
    checkout_confirm_p1_starter: "Ich bestätige die Richtigkeit der Daten",
    checkout_btn_continue: "Weiter",
    checkout_required_fields: "* Pflichtfelder",
    b6_title: "Risiken & Hinweise",
    b6_lead: "Ein Statuswechsel ist ein komplexer Prozess. Das sollten Sie wissen.",
    b6_consequence: "Folge",
    b6_meaning: "Bedeutung",
    b6_solution_label: "Unsere Lösung",
    b6_steps: "Jeder Schritt wird individuell analysiert",
    b6_accent_1: "Ihr Status §24 ist vorübergehend",
    b6_accent_2: "Wir helfen Ihnen, ihn dauerhaft zu sichern",
    b6_r1_t: "Ablehnung des Wechsels",
    b6_r1_c: "Zeit- und Geldverlust",
    b6_r1_d: "Die Behörde kann ablehnen, wenn Bedingungen nicht erfüllt sind.",
    b6_r1_s: "Wir prüfen alles vor der Einreichung.",
    b6_r2_t: "Unzureichendes Einkommen",
    b6_r2_c: "Blockade des Wechsels",
    b6_r2_d: "Viele Titel erfordern ein stabiles Einkommen für die Familie.",
    b6_r2_s: "Wir berechnen den Bedarf individuell.",
    b6_r3_t: "Diplom-Probleme",
    b6_r3_c: "Kein Arbeitsvisum möglich",
    b6_r3_d: "Das Diplom muss in Deutschland anerkannt sein (Anabin).",
    b6_r3_s: "Wir prüfen Ihr Diplom in der Anabin-Datenbank.",
    b6_r4_t: "Bearbeitungsverzögerungen",
    b6_r4_c: "Ungewissheit",
    b6_r4_d: "Behörden sind überlastet, Verfahren dauern oft Monate.",
    b6_r4_s: "Wir nutzen rechtliche Mittel zur Beschleunigung.",
    b6_r5_t: "Sprachanforderungen",
    b6_r5_c: "Nichterfüllung der Kriterien",
    b6_r5_d: "Oft ist ein B1-Zertifikat oder höher erforderlich.",
    b6_r5_s: "Wir nennen das erforderliche Niveau für Ihren Weg.",
    b6_r6_t: "Familiäre Umstände",
    b6_r6_c: "Strategieänderung",
    b6_r6_d: "Die Familiengröße beeinflusst Wohnraum- und Geldvorgaben.",
    b6_r6_s: "Wir analysieren den Fall der gesamten Familie.",
    final_cta_title: "Bereit für den Weg zum Daueraufenthalt?",
    final_cta_lead: "Warten Sie nicht bis 2027. Beginnen Sie heute.",
    final_cta_btn: "Individuelle Strategie erhalten",
    final_cta_sub: "Zahlung über sicheres Stripe-Gateway",
    final_cta_trust: "Vertrauen Sie den Profis von Klamert & Partner",
    faq_title: "Häufig gestellte Fragen",
    faq_q1: "Was, если das Ergebnis negativ ist?",
    faq_a1: "Wir zeigen auf, was Sie tun müssen, um die Bedingungen künftig zu erfüllen.",
    faq_q2: "Wie lange dauert die Analyse?",
    faq_a2: "Normalerweise erhalten Sie das Ergebnis innerhalb von 24-48 Stunden.",
    faq_q3: "Kann ich direkt auf ПМЖ beantragen?",
    faq_a3: "Dies hängt von Einkommen und Sprachniveau ab. Die Analyse zeigt Ihre Chancen.",
    faq_q4: "Was, если ich einen Job, aber kein Diplom habe?",
    faq_a4: "Es gibt Wege für Fachkräfte mit Erfahrung. Wir prüfen Ihre Möglichkeiten.",
    faq_q5: "Warum muss ich erst das Starter-Paket kaufen?",
    faq_a5: "Ohne Analyse können wir nicht verantwortungsvoll über gangbare Wege urteilen.",
    faq_q6: "Sind meine Daten sicher?",
    faq_a6: "Ja, wir nutzen verschlüsselte Verbindungen und halten uns an die DSGVO.",
    faq_q7: "Kann я meine Eltern einschließen?",
    faq_a7: "In der Regel gehören Eltern nicht zur Kern-Bedarfsgemeinschaft.",
    faq_footer: "Unser Ziel ist ein klarer und sicherer Weg für Sie.",
    footer_brand_desc: "Anwalts-Service für den Wechsel von § 24 AufenthG zu dauerhaften Titeln.",
    footer_legal_title: "Rechtliche Informationen",
    footer_bottom_text: "SICHERHEIT. KLARHEIT. ERGEBNIS.",
    footer_link_impressum: "Impressum",
    footer_link_datenschutz: "Datenschutz",
    footer_link_agb: "AGB",
    footer_link_widerruf: "Widerruf",
    footer_link_preise: "Preise",
    footer_anbieter_title: "Anbieter",
    footer_anbieter_name: "Kanzlei Klamert & Partner",
    footer_anbieter_addr: "München, Deutschland",
    footer_anbieter_phone: "+49 (0) 89 123 456",
    footer_anbieter_contact: "contact@paragraf24.de",
    footer_anbieter_chamber: "Eingetragen bei der RAK München",
    footer_anbieter_title_professional: "Rechtsanwälte (BRD)",
    footer_notice_title: "Wichtiger Hinweis",
    footer_notice_text: "Die Informationen auf dieser Seite stellen keine Rechtsberatung dar, bis ein Mandat erteilt wurde.",
    proc_title: "Der Prozess",
    proc_subtitle: "Drei Schritte zu Ihrem neuen Status",
    proc_step1_title: "Analyse",
    proc_step1_desc: "Ermittlung der besten Wechseloptionen.",
    proc_step2_title: "Einreichung",
    proc_step2_desc: "Vorbereitung der Unterlagen für die Behörde.",
    proc_step3_title: "Begleitung",
    proc_step3_desc: "Anwaltliche Unterstützung bei Verzögerungen.",
    proc_bottom: "Die Analyse ist die Basis für jeden Wechsel.",
    aud_title: "Wem wir helfen",
    aud_subtitle: "Wir helfen denen, die ihren Status dauerhaft sichern wollen",
    aud_box_title: "Sie sind in Deutschland nach §24 und:",
    aud_list_1: "Haben Arbeit oder ein Angebot",
    aud_list_2: "Haben ein eigenes Geschäft",
    aud_list_3: "Studieren oder planen dies",
    aud_list_4: "Haben Familie in Deutschland",
    aud_list_5: "Beherrschen die Sprache",
    aud_quote: "«Ihre Aufgabe ist die Integration, unsere ist die rechtliche Absicherung Ihres Erfolgs»"
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ua');

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['ua'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
